### ISSUE TITLE
Autnick Item not working 1.8

### ISSUE THREAD

**Issue by Ruben54213** [Seltrox/AutoNick#6]
21:27:14 WARN]: Exception in thread "Craft Scheduler Thread - 8" 
[21:27:14 WARN]: org.apache.commons.lang.UnhandledException: Plugin AutoNick v1.4.2 generated an exception while executing task 153
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at de.seltrox.autonick.mysql.MySql.query(MySql.java:73)
        at de.seltrox.autonick.AutoNickAPI.lambda$getPlayerInformation$7(AutoNickAPI.java:585)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more

**Comment by Ruben54213** [comment]
[21:38:43 WARN]: Exception in thread "Craft Scheduler Thread - 5" 
[21:38:43 WARN]: org.apache.commons.lang.UnhandledException: Plugin AutoNick v1.4.2 generated an exception while executing task 89
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at de.seltrox.autonick.mysql.MySql.query(MySql.java:73)
        at de.seltrox.autonick.AutoNickAPI.lambda$getPlayerInformation$7(AutoNickAPI.java:585)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
[21:38:45 WARN]: Exception in thread "Craft Scheduler Thread - 11" 
[21:38:45 WARN]: org.apache.commons.lang.UnhandledException: Plugin AutoNick v1.4.2 generated an exception while executing task 109
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
        at de.seltrox.autonick.mysql.MySql.query(MySql.java:73)
        at de.seltrox.autonick.AutoNickAPI.lambda$getPlayerInformation$7(AutoNickAPI.java:585)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
        at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
        ... 3 more
